mixed-port: 7890
allow-lan: true
bind-address: '*'
lan-allowed-ips:
- 127.0.0.0/8
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
mode: rule
log-level: error
ipv6: false
find-process-mode: 'off'
unified-delay: true
tcp-concurrent: true
keep-alive-idle: 15
keep-alive-interval: 15
disable-keep-alive: false
external-controller: 127.0.0.1:9090
secret: ''
external-ui: ./ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  udp-timeout: 300
  endpoint-independent-nat: false
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  cache-algorithm: arc
  prefer-h3: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  nameserver:
  - https://1.1.1.1/dns-query#🚀 节点选择
  - https://8.8.8.8/dns-query#🚀 节点选择
  direct-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  direct-nameserver-follow-policy: true
  nameserver-policy:
    rule-set:domestic:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    rule-set:apple_cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - rule-set:fake_ip_filter
proxy-providers:
  Airport:
    type: http
    url: https://example.com/your-subscription
    path: ./proxy_providers/airport.yaml
    interval: 21600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      udp: true
  SelfBuilt:
    type: file
    path: ./providers/selfbuilt.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      udp: true
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - 🌐 联合自动
  - ♻️ 自动选择
  - 🔯 故障转移
  - 🏠 自建节点
  - 🏠 自建自动
  - 🏠 自建故障
  - 🇭🇰 香港自动
  - 🇹🇼 台湾自动
  - 🇯🇵 日本自动
  - 🇸🇬 新加坡自动
  - 🇺🇸 美国自动
  - DIRECT
  use:
  - Airport
- name: ♻️ 自动选择
  type: url-test
  use:
  - Airport
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|官网|客服|群组|订阅)
- name: 🔯 故障转移
  type: fallback
  use:
  - Airport
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  lazy: true
  expected-status: 204
  max-failed-times: 3
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
- name: 🌐 联合自动
  type: url-test
  use:
  - Airport
  - SelfBuilt
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
  empty-fallback: DIRECT
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
- name: 🏠 自建节点
  type: select
  use:
  - SelfBuilt
- name: 🏠 自建自动
  type: url-test
  use:
  - SelfBuilt
  empty-fallback: DIRECT
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🏠 自建故障
  type: fallback
  use:
  - SelfBuilt
  empty-fallback: DIRECT
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🇭🇰 香港自动
  type: url-test
  use:
  - Airport
  filter: (?i)(香港|港|HK|Hong[ _.-]?Kong)
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🇹🇼 台湾自动
  type: url-test
  use:
  - Airport
  filter: (?i)(台湾|臺灣|台灣|TW|Taiwan)
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🇯🇵 日本自动
  type: url-test
  use:
  - Airport
  filter: (?i)(日本|JP|Japan|Tokyo|Osaka|东京|大阪)
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🇸🇬 新加坡自动
  type: url-test
  use:
  - Airport
  filter: (?i)(新加坡|狮城|SG|Singapore)
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🇺🇸 美国自动
  type: url-test
  use:
  - Airport
  filter: (?i)(美国|美國|US|USA|United[ _.-]?States|Los[ _.-]?Angeles|San[ _.-]?Jose|Seattle|Dallas|New[ _.-]?York|洛杉矶|圣何塞|西雅图)
  exclude-filter: (?i)(官网|套餐|流量|剩余|到期|Expire|Traffic|客服|群组|订阅)
  url: https://www.gstatic.com/generate_204
  interval: 300
  timeout: 5000
  tolerance: 50
  lazy: true
  expected-status: 204
  max-failed-times: 3
- name: 🤖 AI
  type: select
  proxies:
  - 🇺🇸 美国自动
  - 🇯🇵 日本自动
  - 🇸🇬 新加坡自动
  - 🏠 自建节点
  - 🏠 自建自动
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 🎬 流媒体
  type: select
  proxies:
  - 🚀 节点选择
  - 🇭🇰 香港自动
  - 🇹🇼 台湾自动
  - 🇯🇵 日本自动
  - 🇸🇬 新加坡自动
  - 🇺🇸 美国自动
  - 🏠 自建节点
  - 🏠 自建自动
  - ♻️ 自动选择
- name: 📲 Telegram
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - 🇸🇬 新加坡自动
  - 🇺🇸 美国自动
  - 🏠 自建节点
  - 🏠 自建自动
- name: 🐙 GitHub
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - DIRECT
- name: 🍎 Apple
  type: select
  proxies:
  - DIRECT
  - 🚀 节点选择
  - ♻️ 自动选择
- name: Ⓜ️ Microsoft
  type: select
  proxies:
  - DIRECT
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 📥 大文件下载
  type: select
  proxies:
  - DIRECT
  - 🏠 自建自动
  - 🌐 联合自动
  - 🚀 节点选择
- name: 📦 CDN
  type: select
  proxies:
  - 🌐 联合自动
  - 🏠 自建自动
  - 🚀 节点选择
  - DIRECT
- name: ☁️ 系统 CDN
  type: select
  proxies:
  - DIRECT
  - 🏠 自建自动
  - 🌐 联合自动
  - 🚀 节点选择
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - 🚀 节点选择
  - 🌐 联合自动
  - ♻️ 自动选择
  - 🏠 自建节点
  - 🏠 自建自动
  - DIRECT
rule-providers:
  fake_ip_filter:
    type: http
    behavior: domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/clash_fake_ip_filter.txt
    path: ./rules/fake_ip_filter.txt
    interval: 43200
  reject:
    type: http
    behavior: domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/reject.txt
    path: ./rules/reject.txt
    interval: 43200
  reject_drop:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt
    path: ./rules/reject_drop.txt
    interval: 43200
  reject_no_drop:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt
    path: ./rules/reject_no_drop.txt
    interval: 43200
  reject_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/reject.txt
    path: ./rules/reject_ip.txt
    interval: 43200
  download:
    type: http
    behavior: domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
    path: ./rules/download.txt
    interval: 43200
  download_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/download.txt
    path: ./rules/download_ip.txt
    interval: 43200
  cdn:
    type: http
    behavior: domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./rules/cdn.txt
    interval: 43200
  cdn_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/cdn.txt
    path: ./rules/cdn_ip.txt
    interval: 43200
  apple_cdn:
    type: http
    behavior: domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
    path: ./rules/apple_cdn.txt
    interval: 43200
  microsoft_cdn:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./rules/microsoft_cdn.txt
    interval: 43200
  lan:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./rules/lan.txt
    interval: 43200
  direct:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
    path: ./rules/direct.txt
    interval: 43200
  domestic:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
    path: ./rules/domestic.txt
    interval: 43200
  global:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./rules/global.txt
    interval: 43200
  ai:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./rules/ai.txt
    interval: 43200
  ai_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/ai.txt
    path: ./rules/ai_ip.txt
    interval: 43200
  stream:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/stream.txt
    path: ./rules/stream.txt
    interval: 43200
  stream_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/stream.txt
    path: ./rules/stream_ip.txt
    interval: 43200
  telegram:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
    path: ./rules/telegram.txt
    interval: 43200
  telegram_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/telegram.txt
    path: ./rules/telegram_ip.txt
    interval: 43200
  apple_cn:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
    path: ./rules/apple_cn.txt
    interval: 43200
  apple_services:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
    path: ./rules/apple_services.txt
    interval: 43200
  apple_services_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/apple_services.txt
    path: ./rules/apple_services_ip.txt
    interval: 43200
  microsoft:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./rules/microsoft.txt
    interval: 43200
  china_ip:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
    path: ./rules/china_ip.txt
    interval: 43200
rules:
- RULE-SET,reject_drop,REJECT-DROP
- RULE-SET,reject_no_drop,REJECT
- RULE-SET,reject,REJECT
- RULE-SET,reject_ip,REJECT
- RULE-SET,lan,DIRECT
- RULE-SET,direct,DIRECT
- RULE-SET,download,📥 大文件下载
- RULE-SET,download_ip,📥 大文件下载,no-resolve
- RULE-SET,apple_cdn,☁️ 系统 CDN
- RULE-SET,microsoft_cdn,☁️ 系统 CDN
- RULE-SET,cdn,📦 CDN
- RULE-SET,cdn_ip,📦 CDN,no-resolve
- RULE-SET,ai,🤖 AI
- RULE-SET,ai_ip,🤖 AI,no-resolve
- RULE-SET,telegram,📲 Telegram
- RULE-SET,telegram_ip,📲 Telegram,no-resolve
- RULE-SET,stream,🎬 流媒体
- RULE-SET,stream_ip,🎬 流媒体,no-resolve
- DOMAIN-SUFFIX,github.com,🐙 GitHub
- DOMAIN-SUFFIX,githubusercontent.com,🐙 GitHub
- DOMAIN-SUFFIX,githubassets.com,🐙 GitHub
- DOMAIN-SUFFIX,github.io,🐙 GitHub
- RULE-SET,apple_cn,DIRECT
- RULE-SET,apple_services,🍎 Apple
- RULE-SET,apple_services_ip,🍎 Apple,no-resolve
- RULE-SET,microsoft,Ⓜ️ Microsoft
- RULE-SET,domestic,DIRECT
- RULE-SET,china_ip,DIRECT,no-resolve
- RULE-SET,global,🚀 节点选择
- GEOIP,CN,DIRECT,no-resolve
- MATCH,🐟 漏网之鱼
